// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzsThd7NLeoZ-O0MGHVpAGKH85dmYsMWg',
    appId: '1:1052260463649:web:549c46106fb1686b411f60',
    messagingSenderId: '1052260463649',
    projectId: 'trabalhomobilemusikmotion',
    authDomain: 'trabalhomobilemusikmotion.firebaseapp.com',
    databaseURL: 'https://trabalhomobilemusikmotion-default-rtdb.firebaseio.com',
    storageBucket: 'trabalhomobilemusikmotion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq6v9-wlrEx5YyQ_uEzoPehg1GLs3wT4c',
    appId: '1:1052260463649:android:424a8fb47dc000eb411f60',
    messagingSenderId: '1052260463649',
    projectId: 'trabalhomobilemusikmotion',
    databaseURL: 'https://trabalhomobilemusikmotion-default-rtdb.firebaseio.com',
    storageBucket: 'trabalhomobilemusikmotion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDE_desxgbkhMsNC6o9uRWH0kG8TxwhY',
    appId: '1:1052260463649:ios:9814a3b85c0b22f7411f60',
    messagingSenderId: '1052260463649',
    projectId: 'trabalhomobilemusikmotion',
    databaseURL: 'https://trabalhomobilemusikmotion-default-rtdb.firebaseio.com',
    storageBucket: 'trabalhomobilemusikmotion.firebasestorage.app',
    iosBundleId: 'com.example.trabalhomobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzsThd7NLeoZ-O0MGHVpAGKH85dmYsMWg',
    appId: '1:1052260463649:web:ea1c350da0150f81411f60',
    messagingSenderId: '1052260463649',
    projectId: 'trabalhomobilemusikmotion',
    authDomain: 'trabalhomobilemusikmotion.firebaseapp.com',
    databaseURL: 'https://trabalhomobilemusikmotion-default-rtdb.firebaseio.com',
    storageBucket: 'trabalhomobilemusikmotion.firebasestorage.app',
  );
}
